### ISSUE TITLE
module 'ops' has no attribute 'BasicBlock'

### ISSUE THREAD

**Issue by TIMESTICKING** [sym330/UMAG#2]
```
Traceback (most recent call last):
  File "F:/Real-Spec-Spatial-Super-Resolution/comparisons/UMAG/UMAG_demo.py", line 120, in <module>
    need_sigmoid=True, need_bias=True, pad=pad, act_fun='LeakyReLU').type(dtype)
  File "F:\Real-Spec-Spatial-Super-Resolution\comparisons\UMAG\models\UMAG.py", line 70, in __init__
    self.LG = attention_LG(num_channels_down)
  File "F:\Real-Spec-Spatial-Super-Resolution\comparisons\UMAG\models\UMAG.py", line 18, in __init__
    self.c1 = ops.BasicBlock(num_channels_down, num_channels_down // reduction, 3, 1, 3, 3)
AttributeError: module 'ops' has no attribute 'BasicBlock'
```
it happens in UMAG.py, I've searched it up but found nothing.

**Comment by TIMESTICKING** [comment]
it'sok now,need to make 'model' folder as source root
